version: '3'

services:

  backend:
    # tty: true
    image: backend

    build: 
      context: ..
      dockerfile: Dockerfile
      
    volumes: 
      - '..:/var/www/html'
    ports:
      - 81:80
