version: '3'

services:

  backend:
    image: backend

    build: 
      context: ..
      dockerfile: Dockerfile
      
    volumes: 
      - '..:/var/www/html'
    ports:
      - 127.0.0.1:8081:80
